DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS list;
DROP TABLE IF EXISTS final;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE list (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  item_name TEXT NOT NULL,
  cost INTEGER NOT NULL,
  quantity INTEGER,
  selected BOOLEAN
);

CREATE TABLE final (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  item_name TEXT NOT NULL,
  cost INTEGER NOT NULL,
  quantity INTEGER NOT NULL, 
  FOREIGN KEY (id) REFERENCES list (id)
);
